# Limpieza de datos

# Carga del conjunto de datos
#### Puede descargar el conjunto de datos a través del siguiente enlace. _https://www.datos.gov.co/Educaci-n/Saber-11-2018-2/m2nt-jw2h/data_

In [6]:
import pandas as pd
import numpy as np

icfesDatos = pd.read_csv('saber_11_2018.csv') # Lectura del conjunto de datos

#Selección de las características que se usarán en el proyecto.
nuevo =icfesDatos[['ESTU_GENERO','ESTU_DEPTO_RESIDE','FAMI_ESTRATOVIVIENDA','FAMI_TIENEINTERNET', 'FAMI_TIENESERVICIOTV','FAMI_TIENECOMPUTADOR','FAMI_SITUACIONECONOMICA','ESTU_DEDICACIONLECTURADIARIA','ESTU_DEDICACIONINTERNET', 'COLE_AREA_UBICACION','PUNT_LECTURA_CRITICA', 'PUNT_MATEMATICAS','PUNT_C_NATURALES', 'PUNT_SOCIALES_CIUDADANAS','PUNT_INGLES', 'PUNT_GLOBAL' ]]
del icfesDatos

# Limpieza

In [8]:


#----------------------------------DEPARTAMENTO ---------------------------------------------
# Por cada departamento se crea un reemplazo de la cadena de caracteres a un valor entero
# Nota : Bogotá es considerada como un departamento
# la función .loc permite seleccionar las filas que cumplan con la condición (primer argumento) y sobreescribe
# en la columna indicada los valores enteros

nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='AMAZONAS', 'ESTU_DEPTO_RESIDE']=1
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='ANTIOQUIA', 'ESTU_DEPTO_RESIDE']=2
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='ARAUCA', 'ESTU_DEPTO_RESIDE']=3
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='ATLANTICO', 'ESTU_DEPTO_RESIDE']=4
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='BOLIVAR', 'ESTU_DEPTO_RESIDE']=5
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='BOYACA', 'ESTU_DEPTO_RESIDE']=6
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='CALDAS', 'ESTU_DEPTO_RESIDE']=7
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='CAQUETA', 'ESTU_DEPTO_RESIDE']=8
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='CASANARE', 'ESTU_DEPTO_RESIDE']=9
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='CAUCA', 'ESTU_DEPTO_RESIDE']=10
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='CESAR', 'ESTU_DEPTO_RESIDE']=11
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='CHOCO', 'ESTU_DEPTO_RESIDE']=12
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='CORDOBA', 'ESTU_DEPTO_RESIDE']=13
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='CUNDINAMARCA', 'ESTU_DEPTO_RESIDE']=14
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='BOGOTA', 'ESTU_DEPTO_RESIDE']=15
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='GUAINIA', 'ESTU_DEPTO_RESIDE']=16
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='GUAVIARE', 'ESTU_DEPTO_RESIDE']=17
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='HUILA', 'ESTU_DEPTO_RESIDE']=18
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='LA GUAJIRA', 'ESTU_DEPTO_RESIDE']=19
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='MAGDALENA', 'ESTU_DEPTO_RESIDE']=20
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='META', 'ESTU_DEPTO_RESIDE']=21
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='NARIÑO', 'ESTU_DEPTO_RESIDE']=22
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='NORTE SANTANDER', 'ESTU_DEPTO_RESIDE']=23
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='PUTUMAYO', 'ESTU_DEPTO_RESIDE']=24
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='QUINDIO', 'ESTU_DEPTO_RESIDE']=25
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='RISARALDA', 'ESTU_DEPTO_RESIDE']=26
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='SAN ANDRES', 'ESTU_DEPTO_RESIDE']=27
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='SANTANDER', 'ESTU_DEPTO_RESIDE']=28
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='SUCRE', 'ESTU_DEPTO_RESIDE']=29
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='TOLIMA', 'ESTU_DEPTO_RESIDE']=30
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='VALLE', 'ESTU_DEPTO_RESIDE']=31
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='VAUPES', 'ESTU_DEPTO_RESIDE']=32
nuevo.loc[nuevo['ESTU_DEPTO_RESIDE']=='VICHADA', 'ESTU_DEPTO_RESIDE']=33



#------------------ Genero ---------------------------------------------
#Si el género del estudiante es Femenino, se reemplaza con el valor entero 0
#Si el género del estudiante  Masculino, se reemplaza con el valor entero 1
nuevo.loc[nuevo['ESTU_GENERO']=='F', 'ESTU_GENERO']=0
nuevo.loc[nuevo['ESTU_GENERO']=='M', 'ESTU_GENERO']=1


# ------------------Estrato --------------------------------------------------
#Reemplazo de los estratos por valores numéricos
#Las personas "Sin Estrato" se consideran como estrato 0
nuevo.loc[nuevo['FAMI_ESTRATOVIVIENDA']=='Sin Estrato', 'FAMI_ESTRATOVIVIENDA']=0
nuevo.loc[nuevo['FAMI_ESTRATOVIVIENDA']=='Estrato 1', 'FAMI_ESTRATOVIVIENDA']=1
nuevo.loc[nuevo['FAMI_ESTRATOVIVIENDA']=='Estrato 2', 'FAMI_ESTRATOVIVIENDA']=2
nuevo.loc[nuevo['FAMI_ESTRATOVIVIENDA']=='Estrato 3', 'FAMI_ESTRATOVIVIENDA']=3
nuevo.loc[nuevo['FAMI_ESTRATOVIVIENDA']=='Estrato 4', 'FAMI_ESTRATOVIVIENDA']=4
nuevo.loc[nuevo['FAMI_ESTRATOVIVIENDA']=='Estrato 5', 'FAMI_ESTRATOVIVIENDA']=5
nuevo.loc[nuevo['FAMI_ESTRATOVIVIENDA']=='Estrato 6', 'FAMI_ESTRATOVIVIENDA']=6


#------------------Familia Internet---------------------------------------------
#Los estudiantes que tengan servicio de internet son asignadas con un valor entero 1
#los estudiantes que no tengan servicio de internet son asignadas con un valor entero 0
nuevo.loc[nuevo['FAMI_TIENEINTERNET']=='Si','FAMI_TIENEINTERNET']=1
nuevo.loc[nuevo['FAMI_TIENEINTERNET']=='No','FAMI_TIENEINTERNET']=0


#------------------Familia Tv-----------------------------------------------------
#Los estudiantes que tengan servicio de  tv son asignados con un valor entero 1
#Los estudiantes que no tengan servicio de  tv son asignados con un valor entero 0
nuevo.loc[nuevo['FAMI_TIENESERVICIOTV']=='Si','FAMI_TIENESERVICIOTV']=1
nuevo.loc[nuevo['FAMI_TIENESERVICIOTV']=='No','FAMI_TIENESERVICIOTV']=0


# ---------------- Familia Computador---------------------------------------------
#Los estudiantes que tengan computador son asignados con un valor entero 1
#Los estudiantes que no tengan computador son asignados con un valor entero 0
nuevo.loc[nuevo['FAMI_TIENECOMPUTADOR']=='Si','FAMI_TIENECOMPUTADOR']=1
nuevo.loc[nuevo['FAMI_TIENECOMPUTADOR']=='No','FAMI_TIENECOMPUTADOR']=0


#----------------- Familia Situación Economica---------------------------------------------
#Los estudiantes con situación económica Peor son asignados con un valor entero 0
#Los estudiantes con situación económica Igual son asignados con un valor entero 1
#Los estudiantes con situación económica Mejor son asignados con un valor entero 2
nuevo.loc[nuevo['FAMI_SITUACIONECONOMICA']=='Peor','FAMI_SITUACIONECONOMICA']=0
nuevo.loc[nuevo['FAMI_SITUACIONECONOMICA']=='Igual','FAMI_SITUACIONECONOMICA']=1
nuevo.loc[nuevo['FAMI_SITUACIONECONOMICA']=='Mejor','FAMI_SITUACIONECONOMICA']=2

# ---------------- Estudio Lectura Diaria---------------------------------------------
# Promedio entre los rangos extremos. Se asume que menos de 30 minutos son 15 minutos
# Para la dedicación de lectura diaria superior a 2 horas, se supone en 120 minutos
nuevo.loc[nuevo['ESTU_DEDICACIONLECTURADIARIA']=='30 minutos o menos','ESTU_DEDICACIONLECTURADIARIA'] = 15
nuevo.loc[nuevo['ESTU_DEDICACIONLECTURADIARIA']=='Entre 30 y 60 minutos','ESTU_DEDICACIONLECTURADIARIA'] = 45
nuevo.loc[nuevo['ESTU_DEDICACIONLECTURADIARIA']=='Entre 1 y 2 horas','ESTU_DEDICACIONLECTURADIARIA'] = 90
nuevo.loc[nuevo['ESTU_DEDICACIONLECTURADIARIA']=='Más de 2 horas','ESTU_DEDICACIONLECTURADIARIA'] = 120
nuevo.loc[nuevo['ESTU_DEDICACIONLECTURADIARIA']=='No leo por entretenimiento','ESTU_DEDICACIONLECTURADIARIA'] = 0

#----------------- Estudio Dedicacion Internet---------------------------------------------
#Se asume que si el estudiante navega menos de 30 minutos se asume como 15 minutos.
#Se asume que si el estudiante navega más de 1 y 3 horas se asume como 180 minutos
nuevo.loc[nuevo['ESTU_DEDICACIONINTERNET']=='No Navega Internet', 'ESTU_DEDICACIONINTERNET']=0
nuevo.loc[nuevo['ESTU_DEDICACIONINTERNET']=='30 minutos o menos', 'ESTU_DEDICACIONINTERNET']=15
nuevo.loc[nuevo['ESTU_DEDICACIONINTERNET']=='Entre 30 y 60 minutos', 'ESTU_DEDICACIONINTERNET']=45
nuevo.loc[nuevo['ESTU_DEDICACIONINTERNET']=='Entre 1 y 3 horas', 'ESTU_DEDICACIONINTERNET']=120
nuevo.loc[nuevo['ESTU_DEDICACIONINTERNET']=='Más de 3 horas', 'ESTU_DEDICACIONINTERNET']=180

# ---------------- Area del colegio ---------------------------------------------------------
#Si la ubicación del colegio del estudiante es rural se reemplaza con un valor entero 1
#Si la ubicación del colegio del estudiante es urbano se reemplaza con el valor entero 0
nuevo.loc[nuevo['COLE_AREA_UBICACION']=='RURAL','COLE_AREA_UBICACION']=1
nuevo.loc[nuevo['COLE_AREA_UBICACION']=='URBANO','COLE_AREA_UBICACION']=0

In [9]:
#Se elimina el registro en donde exista el caracter '-' en cualquiera de las características.
#Se elimina el registro en donde exista un estudiante "Extranjero" en la característica "ESTU_DEPTO_RESIDE"
nuevo = nuevo[nuevo.FAMI_ESTRATOVIVIENDA !='-']
nuevo = nuevo[nuevo.FAMI_TIENEINTERNET !='-']
nuevo = nuevo[nuevo.FAMI_SITUACIONECONOMICA !='-']
nuevo = nuevo[nuevo.FAMI_TIENECOMPUTADOR !='-']
nuevo = nuevo[nuevo.ESTU_DEDICACIONLECTURADIARIA !='-']
nuevo = nuevo[nuevo.ESTU_DEDICACIONINTERNET !='-']
nuevo = nuevo[nuevo.FAMI_TIENESERVICIOTV !='-']
nuevo = nuevo[nuevo.ESTU_DEPTO_RESIDE !='EXTRANJERO']

In [10]:
#Reinicia los índices para el conjunto de datos ya modificado
nuevo = nuevo.reset_index(drop=True)

In [11]:
nuevo.head()

,ESTU_GENERO,ESTU_DEPTO_RESIDE,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_TIENESERVICIOTV,FAMI_TIENECOMPUTADOR,FAMI_SITUACIONECONOMICA,ESTU_DEDICACIONLECTURADIARIA,ESTU_DEDICACIONINTERNET,COLE_AREA_UBICACION,PUNT_LECTURA_CRITICA,PUNT_MATEMATICAS,PUNT_C_NATURALES,PUNT_SOCIALES_CIUDADANAS,PUNT_INGLES,PUNT_GLOBAL
0,1,4,2,1,1,0,1,15,180,0,63,69,54,57,65.0,305
1,1,13,1,1,1,0,2,45,45,0,54,50,50,40,48.0,242
2,1,31,2,0,0,0,2,15,45,1,59,43,46,45,47.0,241
3,1,6,3,1,1,1,1,15,180,0,61,60,60,67,63.0,310
4,1,15,2,1,1,0,1,15,120,0,56,51,48,49,56.0,257

# Selección de las características y las etiquetas

In [12]:
x = nuevo[['ESTU_GENERO','ESTU_DEPTO_RESIDE','FAMI_ESTRATOVIVIENDA','FAMI_TIENEINTERNET', 'FAMI_TIENESERVICIOTV' ,'FAMI_TIENECOMPUTADOR','FAMI_SITUACIONECONOMICA','ESTU_DEDICACIONLECTURADIARIA','ESTU_DEDICACIONINTERNET', 'COLE_AREA_UBICACION', 'PUNT_LECTURA_CRITICA','PUNT_MATEMATICAS','PUNT_C_NATURALES','PUNT_SOCIALES_CIUDADANAS','PUNT_INGLES','PUNT_GLOBAL']]

In [13]:
x[:5]

,ESTU_GENERO,ESTU_DEPTO_RESIDE,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_TIENESERVICIOTV,FAMI_TIENECOMPUTADOR,FAMI_SITUACIONECONOMICA,ESTU_DEDICACIONLECTURADIARIA,ESTU_DEDICACIONINTERNET,COLE_AREA_UBICACION,PUNT_LECTURA_CRITICA,PUNT_MATEMATICAS,PUNT_C_NATURALES,PUNT_SOCIALES_CIUDADANAS,PUNT_INGLES,PUNT_GLOBAL
0,1,4,2,1,1,0,1,15,180,0,63,69,54,57,65.0,305
1,1,13,1,1,1,0,2,45,45,0,54,50,50,40,48.0,242
2,1,31,2,0,0,0,2,15,45,1,59,43,46,45,47.0,241
3,1,6,3,1,1,1,1,15,180,0,61,60,60,67,63.0,310
4,1,15,2,1,1,0,1,15,120,0,56,51,48,49,56.0,257

In [23]:
#Generación del conjunto de datos en un archivo
x.to_csv('Datos/datos', index=False)